name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: "hyunbin7303@email.com"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hblog-web-api"
          useforce: true,
          dynamicFiles: true,
          procfile: "worker: npm start"
